### ISSUE TITLE
error while trying to run the project

### ISSUE THREAD

**Issue by y9luiz** [WallysonGalvao/rocketseat-gobarber#6]
After the setup steps i tried to run the project but it couldn't be done for some reason... anyone knows this error and know how i could fix it?

`
yarn run v1.22.5
$ ts-node src/shared/infra/http/server.ts
Error: Cannot find module '@config/upload'
Require stack:
- /home/luiz/Projects/GoBarber/rocketseat-gobarber/backend/src/shared/infra/http/app.ts
- /home/luiz/Projects/GoBarber/rocketseat-gobarber/backend/src/shared/infra/http/server.ts
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/luiz/Projects/GoBarber/rocketseat-gobarber/backend/src/shared/infra/http/app.ts:8:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Module.m._compile (/home/luiz/Projects/GoBarber/rocketseat-gobarber/backend/node_modules/ts-node/src/index.ts:836:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.require.extensions.<computed> [as .ts] (/home/luiz/Projects/GoBarber/rocketseat-gobarber/backend/node_modules/ts-node/src/index.ts:839:12)
    at Module.load (internal/modules/cjs/loader.js:863:32)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`

**Comment by apiresian** [comment]
Still not working, same error.
